# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wylogger < Formula
  desc "A tool for automatically authenticate the network of Wen Yuan Talent Apartment."
  homepage "https://github.com/mafuka/wylogger"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.5/wylogger_darwin_amd64.tar.gz"
      sha256 "e78a94ad2c1015a31b41a624a5f65e2fbe03da961f455dd64b84121c02726ee6"

      def install
        bin.install "wylogger"
        prefix.install "config.example.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.5/wylogger_darwin_arm64.tar.gz"
      sha256 "ff9039ff21d147c71d41e557d46ec228440c53bc440668f03f9930c6c3b7dd6d"

      def install
        bin.install "wylogger"
        prefix.install "config.example.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.5/wylogger_linux_amd64.tar.gz"
      sha256 "ad760f5d49b885a566e578e271cce27be0b30041ca41542fa3ce89516ff760c1"

      def install
        bin.install "wylogger"
        prefix.install "config.example.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.5/wylogger_linux_arm64.tar.gz"
      sha256 "dbaab44974bc0a7db6b1f4d5a3aeb2ca0560aa78f8583dfe6008dba2a3805418"

      def install
        bin.install "wylogger"
        prefix.install "config.example.yml"
      end
    end
  end

  def post_install
    (etc/"wylogger").mkpath
    unless (etc/"wylogger/config.yml").exist?
      cp opt_prefix/"config.example.yml", etc/"wylogger/config.yml"
    end
    puts "Please customize your configuration file at #{etc/"wylogger/config.yml"}"
  end
end
