# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wylogger < Formula
  desc "A tool for automatically authenticate the network of Wen Yuan Talent Apartment."
  homepage "https://github.com/mafuka/wylogger"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.4/wylogger_darwin_arm64.tar.gz"
      sha256 "cac3c64753959a6049ce13dda6faf037a97e85e60cc868c8427e8e5e9527a45e"

      def install
        bin.install "wylogger"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.4/wylogger_darwin_amd64.tar.gz"
      sha256 "6143b6c057754508c189bae94b47af2e162e60ce01e098e3d249943e50ace83c"

      def install
        bin.install "wylogger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.4/wylogger_linux_arm64.tar.gz"
      sha256 "45d915606c0c4a3571a5fcd3f4eb9cd36804b3d9785aa2bd41b3a22e3fe31049"

      def install
        bin.install "wylogger"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mafuka/wylogger/releases/download/0.1.4/wylogger_linux_amd64.tar.gz"
      sha256 "4c715c8a1c9e2d8c113a9ad191808a474a196169564c589b629151e800104fda"

      def install
        bin.install "wylogger"
      end
    end
  end

  def post_install
    (etc/"wylogger").mkpath
    unless (etc/"wylogger/config.yml").exist?
      cp prefix/"config.example.yml", etc/"wylogger/config.yml"
    end
    puts "Please customize your configuration file at #{etc/"wylogger/config.yml"}"
  end
end
